language: rust
rust: [stable, beta, nightly]

branches:
  only: [master]

env:
  - RUSTFLAGS="-D warnings" RUST_BACKTRACE="1" RUST_LOG="tokio_i3ipc=trace"

before_install:
  - >
    rustup self update &&
    rustup component add rustfmt clippy

matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

cache:
  cargo: true
  directories:
    - $HOME/.local/share/

script:
  - '[ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo fmt --all -- --check'

  - cargo clippy --all --tests --examples -- --deny clippy::all;

  - cargo test -- --nocapture;

  - cargo test --doc README;
