language: rust
rust:
  - stable
  - nightly

branches:
  only:
    - master

before_install:
  - export RUSTFLAGS="-D warnings"
  # - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
  #   rustup self update &&
  #   rustup component add rustfmt clippy &&
  #   cargo clippy --version;
  #   fi

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  cargo: true
  directories:
    - $HOME/.local/share/

script:
  # - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
  #   fi
  - for dir in tokio-i3ipc i3ipc-types i3-ipc async-i3ipc; do
    env RUST_BACKTRACE=1 RUST_LOG=tokio_i3ipc=trace cargo test --manifest-path $dir/Cargo.toml -- --nocapture;
    cargo fmt --all -- --check && cargo clippy --all --tests --examples -- --deny clippy::all;
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test --doc README; fi
    done
